# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  watch:
    cmds:
      - pnpm watch
  
  run: 
    cmds: 
      - go run main.go

